name: Stage Azure deploy

on:
  push:
    branches:
      - stage-cicd

env: 
  BACKEND_ENVIRONMENT_STAGE: ${{ vars.BACKEND_ENVIRONMENT_STAGE }}
  BACKEND_ENVIRONMENT_STAGE_URL: ${{ vars.BACKEND_ENVIRONMENT_STAGE_URL }}
  APP_VERSION_PREFIX_STAGE: ${{ vars.APP_VERSION_PREFIX_STAGE }}
  AZURE_STORAGE_ACCOUNT_PROD: ${{ vars.AZURE_STORAGE_ACCOUNT_STAGE }}
  AZURE_STORAGE_CONTAINER_NAME_PRESTA: ${{ vars.AZURE_STORAGE_CONTAINER_NAME_PRESTA }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  version:
    name: Version bump
    uses: ./.github/workflows/stage-version.yml

  build-app:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Fetch latest changes
      run: |
        git fetch origin
        git reset --hard origin/stage-cicd

    - name: Replace version in simplyin.php
      run: |
        VERSION=$(jq -r '.version' package.json)
        sed '0,/$this->version/{s/$this->version.*/$this->version = "'$VERSION'";/}' simplyin.php > temp && mv temp simplyin.php
        sed -i 's|$this->description =.*|$this->description = "simplyin module - quick checkout process ${{ env.APP_VERSION_PREFIX_STAGE }}";|g' simplyin.php

    - name: Replace $backend_url in simplyin.php and api/submitData.php
      run: |
        sed -i 's|$backend_url =.*|$backend_url = "${{ env.BACKEND_ENVIRONMENT_STAGE_URL }}";|g' simplyin.php
        sed -i 's|$backend_url =.*|$backend_url = "${{ env.BACKEND_ENVIRONMENT_STAGE_URL }}";|g' api/submitData.php
        
    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git commit -am "Update backend environment variable" || exit 0
        git push

    - name: Dependencies install 
      run: |
        cd views/js/react-app
        yarn install

    - name: Create react app bundle 
      run: |
        cd views/js/react-app
        yarn deploy-build
    
    - name: Remove unnecessary files
      run: |
        rm -rf .git
        rm -rf .github
        rm -rf .gitignore
        rm -rf vendor
        rm -rf .php-cs-fixer.cache
        rm -rf .php-cs-fixer.dist.php
        rm -rf setup_php_cs_fixer.sh
        cd views/js/react-app
        rm -rf src
        rm -rf node_modules

    - name: Create simplyin directory and move files
      run: |
        mkdir simplyin
        shopt -s extglob
        mv !(simplyin) simplyin

    - name: Zip the simplyin directory
      run: |
        zip -r simplyin-stage-presta.zip simplyin

    - name: Upload zip file
      uses: actions/upload-artifact@v2
      with:
        name: simplyin-stage-presta
        path: simplyin-stage-presta.zip

  deploy-zip-file-in-azure:
    runs-on: ubuntu-latest
    needs: [build-app]

    steps:
    - name: Download zip file
      uses: actions/download-artifact@v2
      with:
        name: simplyin-stage-presta
        path: .

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
    
    - name: Upload files to Azure Storage
      run: |
        az storage blob upload --account-name ${{ env.AZURE_STORAGE_ACCOUNT_PROD }} --container-name ${{ env.AZURE_STORAGE_CONTAINER_NAME_PRESTA }} --file simplyin-stage-presta.zip --name simplyin-stage-presta.zip --auth-mode login --overwrite